# Generated by Django 4.2.4 on 2024-10-26 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('Book_Author', models.CharField(max_length=255)),
                ('Year_of_Publication', models.DateField(blank=True)),
                ('Publisher', models.CharField(max_length=255)),
                ('img', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='book_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.FloatField(blank=True)),
                ('status', models.CharField(choices=[('IN_PROCESS', 'In Process'), ('READ', 'Read')], default='IN_PROCESS', max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book_user',
            },
        ),
    ]
