# Generated by Django 4.2.4 on 2024-10-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Year_of_Publication',
            field=models.CharField(default='', max_length=255),
        ),
    ]
