# Generated by Django 4.2.4 on 2024-10-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Book_Title',
            new_name='title',
        ),
    ]
